#!/usr/bin/env bash
# Download IEEE OUI and write a slim oui_base.txt for OpenWrt packaging.
# Usage:
#   ./scripts/gen-oui.sh                 # write root/usr/share/netnotify/oui_base.txt
#   ./scripts/gen-oui.sh /path/out.txt   # custom output
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/root/usr/share/netnotify/oui_base.txt}"
URL="${OUI_URL:-https://standards-oui.ieee.org/oui/oui.txt}"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "Downloading $URL ..."
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$URL" -o "$TMP"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$TMP" "$URL"
else
  echo "need curl or wget" >&2
  exit 1
fi

# Keep common consumer / IoT related vendors (case-insensitive substring match).
# Override with OUI_KEEP='Apple|Xiaomi|...' if needed.
KEEP_RE="${OUI_KEEP:-Apple|Xiaomi|Huawei|Honor|OPPO|vivo|Samsung|Espressif|TP-LINK|Tp-Link|Tenda|Intel|Realtek|MediaTek|Raspberr|Google|Microsoft|Sony|Nintendo|ASUS|Dell|Lenovo|Murata|AzureWave|Cisco|Ubiquiti|Rivet|Amazon|OnePlus|zte|ZTE|Motorola|LG Electronics|Hewlett Packard|HPE|Fujitsu|Toshiba|Liteon|Hon Hai|Foxconn|Shenzhen|Beijing|Shanghai|espressif|espress}"

python3 - "$TMP" "$OUT" "$KEEP_RE" <<'PY'
import re, sys
src, out, keep = sys.argv[1], sys.argv[2], sys.argv[3]
pat = re.compile(keep, re.I)
# IEEE lines look like:  AA-BB-CC   (base 16)		Vendor Name
line_re = re.compile(r"^([0-9A-Fa-f-]{6,8})\s+\(base 16\)\s+(.+)$")
seen = {}
with open(src, "r", encoding="utf-8", errors="replace") as f:
    for line in f:
        m = line_re.match(line.strip())
        if not m:
            continue
        prefix = m.group(1).replace("-", "").replace(":", "").upper()
        if len(prefix) != 6:
            continue
        name = re.sub(r"\s+", "_", m.group(2).strip())
        name = re.sub(r"[^\w.\-]+", "_", name)
        if not pat.search(name):
            continue
        seen[prefix] = name

with open(out, "w", encoding="utf-8") as f:
    f.write("# Generated by scripts/gen-oui.sh from IEEE OUI\n")
    f.write("# Source: https://standards-oui.ieee.org/oui/oui.txt\n")
    for prefix in sorted(seen):
        f.write(f"{prefix}\t{seen[prefix]}\n")
print(f"wrote {len(seen)} entries -> {out}")
PY
